-- ── SQL DDL untuk Membuat Tabel Relasi Rekomendasi Obat ──
-- Silakan jalankan query ini di SQL Editor dashboard Supabase Anda.

CREATE TABLE IF NOT EXISTS public.rekomendasi_obat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hama_id BIGINT NOT NULL REFERENCES public.hama(id) ON DELETE CASCADE,
    obat_id BIGINT NOT NULL REFERENCES public.obat(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT rekomendasi_obat_unique UNIQUE(hama_id, obat_id)
);

-- Mengaktifkan/Menonaktifkan RLS (Row Level Security)
-- Catatan: Agar fitur berjalan dengan lancar saat login menggunakan kredensial .env (tanpa Supabase Auth),
-- RLS pada tabel ini dapat dinonaktifkan (seperti tabel 'obat' bawaan).
ALTER TABLE public.rekomendasi_obat DISABLE ROW LEVEL SECURITY;
